### ISSUE TITLE
OAuthException - This authorization code has expired. [code=100]

### ISSUE THREAD

**Issue by gpearson** [TheRealAgentK/facebook-cf-sdk#57]
Upon logging out of facebook and trying to login again, getting this error message. Stacktrace is:

OAuthException - This authorization code has expired. [code=100]
    at plugins.eventregistration.library.facebooksdk.sdk.facebookbase_cfc$cf.udfCall1(/var/www/virtuals/eventsdemo.niesc.k12.in.us/html/plugins/EventRegistration/library/FacebookSDK/sdk/FacebookBase.cfc:84):84
    at plugins.eventregistration.library.facebooksdk.sdk.facebookbase_cfc$cf.udfCall(/var/www/virtuals/eventsdemo.niesc.k12.in.us/html/plugins/EventRegistration/library/FacebookSDK/sdk/FacebookBase.cfc):-1
    at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
    at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
    at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
    at railo.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:748):748
    at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
    at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
    at plugins.eventregistration.library.facebooksdk.sdk.facebookgraphapi_cfc$cf.udfCall3(/var/www/virtuals/eventsdemo.niesc.k12.in.us/html/plugins/EventRegistration/library/FacebookSDK/sdk/FacebookGraphAPI.cfc:377):377
    at plugins.eventregistration.library.facebooksdk.sdk.facebookgraphapi_cfc$cf.udfCall(/var/www/virtuals/eventsdemo.niesc.k12.in.us/html/plugins/EventRegistration/library/FacebookSDK/sdk/FacebookGraphAPI.cfc):-1
    at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
    at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
    at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:195):195
    at railo.runtime.ComponentImpl._call(ComponentImpl.java:624):624
    at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
    at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1755):1755
    at railo.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:755):755
    at railo.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1557):1557
    at plugins.eventregistration.library.facebooksdk.sdk.facebookapp_cfc$cf.udfCall3(/var/www/virtuals/eventsdemo.niesc.k12.in.us/html/plugins/EventRegistration/library/FacebookSDK/sdk/FacebookApp.cfc:500):500
    at plugins.eventregistration.library.facebooksdk.sdk.facebookapp_cfc$cf.udfCall(/var/www/virtuals/eventsdemo.niesc.k12.in.us/html/plugins/EventRegistration/library/FacebookSDK/sdk/FacebookApp.cfc):-1
    at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
    at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
    at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
    at railo.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:748):748
    at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
    at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
    at plugins.eventregistration.library.facebooksdk.sdk.facebookapp_cfc$cf.udfCall2(/var/www/virtuals/eventsdemo.niesc.k12.in.us/html/plugins/EventRegistration/library/FacebookSDK/sdk/FacebookApp.cfc:320):320
    at plugins.eventregistration.library.facebooksdk.sdk.facebookapp_cfc$cf.udfCall(/var/www/virtuals/eventsdemo.niesc.k12.in.us/html/plugins/EventRegistration/library/FacebookSDK/sdk/FacebookApp.cfc):-1
    at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:93):93
    at railo.runtime.type.UDFImpl._call(UDFImpl.java:307):307
    at railo.runtime.type.UDFImpl.call(UDFImpl.java:208):208
    at railo.runtime.ComponentImpl._call(ComponentImpl.java:623):623
    at railo.runtime.ComponentImpl._call(ComponentImpl.java:506):506
    at railo.runtime.ComponentImpl.call(ComponentImpl.java:1738):1738
    at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:724):724
    at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1547):1547
    at plugins.eventregistration.library.facebooksdk.examples.app.index_cfm$cf.call(/var/www/virtuals/eventsdemo.niesc.k12.in.us/html/plugins/EventRegistration/library/FacebookSDK/examples/app/index.cfm:43):43
    at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:909):909
    at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:861):861
    at railo.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:206):206
    at railo.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:18):18
    at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2212):2212
    at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2179):2179
    at railo.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:331):331
    at railo.loader.servlet.CFMLServlet.service(CFMLServlet.java:29):29
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727):727
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303):303
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208):208
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52):52
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241):241
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208):208
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220):220
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122):122
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501):501
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170):170
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98):98
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116):116
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408):408
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040):1040
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607):607
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313):313
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145):1145
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615):615
    at java.lang.Thread.run(Thread.java:745):745

The error is a result of the line:

userAccessToken = facebookApp.getUserAccessToken();

When logged out the session is still active. I am trying to debug to assist. In a google search they say to solve this by calling getLoginStatus() but this does not have this function.

**Comment by JonnyHayes** [comment]
https://developers.facebook.com/search/?q=getLoginStatus

**Comment by cfmaniac** [comment]
I found that if you uncomment lines: 47, 58, 60-62 You'll get the prompt to login.
46: if (userId) {
47:     try {
...
58:           } catch (any exception) {
59:         // Usually an invalid session (OAuthInvalidTokenException), for example if the user logged out from facebook.com
            userId = 0;
            facebookGraphAPI = new FacebookGraphAPI();
        }
